### ISSUE TITLE
Add flag to only get non sync lyrics

### ISSUE THREAD

**Issue by calm3285** [lo3me/syncedlyrics#18]
I like plain text lyrics since sometimes they arent correctly synced

**Comment by 0x7d4** [comment]
Did you try `--alow-plain`? If yes and wrong result, then please provide the search term you used to reproduce.

**Comment by calm3285** [comment]
i tried it and got the wrong result twice

syncedlyrics -v --allow-plain "run the jewels ohh la la"
DEBUG:syncedlyrics:Looking for an LRC on Lrclib
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): lrclib.net:443
DEBUG:urllib3.connectionpool:https://lrclib.net:443 "GET /api/search?q=run+the+jewels+ohh+la+la HTTP/1.1" 200 2
DEBUG:syncedlyrics:Looking for an LRC on Musixmatch
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): apic-desktop.musixmatch.com:443
DEBUG:urllib3.connectionpool:https://apic-desktop.musixmatch.com:443 "GET /ws/1.1/track.search?q=run+the+jewels+ohh+la+la&page_size=5&page=1&s_track_rating=desc&quorum_factor=1.0&app_id=web-desktop-app-v1.0&usertoken=231213f3c80877fb509a35670d195f7059fa027148f2b5c369560c&t=1702437306514 HTTP/1.1" 200 119
DEBUG:syncedlyrics:Looking for an LRC on NetEase
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): music.163.com:443
DEBUG:urllib3.connectionpool:https://music.163.com:443 "GET /api/search/pc?limit=10&type=1&offset=0&s=run+the+jewels+ohh+la+la HTTP/1.1" 200 None
DEBUG:syncedlyrics:Looking for an LRC on Megalobiz
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.megalobiz.com:443
DEBUG:urllib3.connectionpool:https://www.megalobiz.com:443 "GET /search/all?qry=run%20the%20jewels%20ohh%20la%20la&searchButton.x=0&searchButton.y=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.megalobiz.com:443 "GET /lrc/maker/The+Family+Jewels.55269921 HTTP/1.1" 200 None
INFO:syncedlyrics:synced-lyrics found for "run the jewels ohh la la" on Megalobiz

[ar:Marina and the Diamonds]
[ti:The Family Jewels]
[length:04:05.57]
[by:rae]
[re:www.megalobiz.com/lrc/maker]
[ve:v1.2.3]
[00:04.77]I can't break the cycle, am I just a fool?
[00:13.12]Falling down like dominoes, hit by family jewels
[00:22.13]Pass it down from kid to kid, the chain will never end
[00:30.37]'Less I decide to go to it, will I see the end?
[00:40.30]Ooh, don't you find it strange?
[00:42.78]Only thing we share is one last name
[00:47.04]Did I beat you at your own game?
[00:51.29]Typical of me to put us all to shame
[00:56.53]Welcome to the family jewels
[01:00.04]Coal to diamond, sold to fools
[01:04.26]Welcome to the family jewels
[01:08.78]Simmerin' sapphire can't keep his cool
[01:12.78]I can't keep my cool
[01:17.53]I can't keep my cool
[01:23.58]Family said that I decided to live a loveless life
[01:29.83]Is it my fault we stay divided? 'Cause I got too much pride
[01:38.56]Pass the parcel, wrap, unwrap, and open up the locks
[01:47.09]Out come flying all the secrets of Pandora's box
[01:56.33]Oh, you think I'm unfit
[01:59.84]Little did you know that I was cut for it
[02:04.07]No glass slipper will ever fit
[02:08.30]'Cause I could never see a diamond in it
[02:13.08]Welcome to the family jewels
[02:17.06]Coal to diamond, sold to fools
[02:21.58]Welcome to the family jewels
[02:25.57]Simmerin' sapphire can't keep his cool
[02:29.83]I can't keep my cool
[02:34.08]I can't keep my cool
[02:38.83]And when we're in the dark, it echoes in your heart
[02:42.83]And when you're far away, it beckons me to stay
[02:55.33]And when we're in the dark, it echoes in your heart
[03:04.83]And when you're far away, it beckons me to stay
[03:14.83]Welcome to the family jewels
[03:18.08]Coal to diamond, sold to fools
[03:22.58]Welcome to the family jewels
[03:26.58]Simmerin' sapphire can't keep his cool
[03:31.08]I can't keep my cool
[03:34.88]I can't keep my cool
[03:35.83]Welcome to the family jewels
[03:36.58]Coal to diamond, sold to fools
[03:38.08]Welcome to the family jewels
[03:43.84]Simmerin' sapphire can't keep his cool
[03:48.58]I can't keep my cool
[03:52.83]I can't keep my cool

**Comment by calm3285** [comment]
I got the remix version. Searching in the site got the first one https://lrclib.net/search/run%20the%20jewels%20ooh%20la%20la

python __main__.py --allow-plain "run the jewels ooh la la"
INFO:syncedlyrics:synced-lyrics found for "run the jewels ooh la la" on Lrclib
[00:00.32] Ooh, la, la, ah, oui, oui
[00:02.63] Ooh, la, la, ah, oui, oui
[00:05.34] Ooh, la, la, ah, oui, oui
[00:08.24] Ooh, la, la
[00:09.60] Yeah, uh
[00:11.50] Ooh, la, la, it's Young Mula-la
[00:13.80] Me no do ra-ra, boom-boom, kumbaya
[00:16.46] Vroom-vroom, zoom by ya, me and all me goon brada
[00:19.36] Mario Brother shroom power make me doom-doom-da-da
[00:22.54] Bougie thot, I call her Bougie Banton
[00:25.15] She like sushi and opera, but her coochie aqua
[00:27.85] What's a goon to a goblin? What's a shooter to a shotter?
[00:30.73] I could boom shakalaka your medulla oblongata
[00:33.38] Kill a mic like El-P and Killer Mike, feeling like
[00:36.08] DJ Premier, it's my world premiere tonight, feeling right
[00:38.90] Hair trigger softer than a pillow fight
[00:41.05] No computer, but this MAC got more shots than gigabytes
[00:44.00] Bigger teeth, bigger bite, bigger holes in the wall
[00:46.67] Money tall, ego small, blunt as long as a log
[00:49.56] Mask is off, nothin' to lose, classy God, Sunday school
[00:52.28] Run up a check and run your mouth, we run you down, Run The Jewels
[00:55.38] Lil Tune
[00:56.44] Ooh, la, la, ah, oui, oui (ayy)
[00:59.01] Ooh, la, la, ah, oui, oui (ah, oui, oui)
[01:02.03] Ooh, la, la, ah, oui, oui
[01:04.61] Ooh, la, la, ah, oui, oui (mon cheri, mon cheri)
[01:07.82] Ooh, la, la, ah, oui, oui
[01:10.14] Ooh, la, la, ah, oui, oui
[01:13.05] Ooh, la, la, ah, oui, oui
[01:16.25] Ooh, la, la
[01:18.32] Lookin' for M's like I lost a friend
[01:20.27] Jump out of my bed like, "Where the bread?"
[01:22.08] You gon' hold the egg, waiter bring the check
[01:23.87] When we talk, we Kalashnikov, keep us in your thoughts
[01:26.89] Fully dressed at the crack of dawn, weapons letting off
[01:29.67] I can hear them from the block, see them creeping through the fog
[01:32.56] Season's greetings, now feeding season can start, oh my God
[01:35.78] Look alive, lookin' like I live life on a crooked line
[01:38.14] Doin' fine, you want maximum stupid, I am the guy
[01:41.03] First of all, fuck the fuckin' law, we is fuckin' raw
[01:43.92] Steak tartare, oysters on the half-shell, sushi bar
[01:46.59] Life a bitch and the pussy fish, still fucked her raw
[01:49.57] I'm a dog, I'm a dirty dog, ha-ha-ha-ha-ha
[01:52.44] Ol' Dirty Bastard, go in your jaw, shimmy shimmy ya
[01:55.17] Got the semi in the hemi, goin', "Gimme, gimme, y'all"
[01:58.05] Pugilistic, my linguistics are Jeru the Damaja
[02:00.95] And I rap it pornographic, bitch, set up the camera
[02:03.80] Ooh, la, la, ah, oui, oui
[02:06.76] Ooh, la, la, ah, oui, oui
[02:09.61] Ooh, la, la, ah, oui, oui (I need a bottle of Moët, hoe, come on)
[02:12.87] Ooh, la, la (garçon)
[02:15.13] You covet disruption, I got you covered, I'm bustin' (bustin')
[02:18.28] My brother's a runner, he crushin', it's no discussion ('scussion)
[02:21.11] I used to be munchkin, I wasn't 'posed to be nothin' (nothin')
[02:24.04] Y'all fuckers corrupted and up to somethin' disgusting
[02:26.73] My pockets are plumper this season, I love to cuff 'em
[02:29.02] I'm afraid of nothin' but nothingness, ain't it something?
[02:32.26] Warmongers are dumpin', they'll point and click at your pumpkin (look out)
[02:35.17] Your suffering is scrumptious, they'll put your kids in the oven
[02:37.75] Fuck a king or queen and all of they loyal subjects
[02:40.61] I pull my penis out and I piss on they shoes in public
[02:43.37] People, we the pirates, the pride of this great republic
[02:46.32] No matter what you order, motherfucker, we what you're stuck with (sorry)
[02:49.50] I used to love Bruce, but livin' my vida loca
[02:51.83] Helped me understand I'm probably more of a Joker
[02:54.72] When we usher in chaos, just know that we did it smiling
[02:57.67] Cannibals on this island, inmates run the asylum
[03:00.60] Ooh, la, la, ah, oui, oui (ayy)
[03:03.21] Ooh, la, la, ah, oui, oui (ayy)
[03:06.12] Ooh, la, la, ah, oui, oui (ayy)
[03:09.03] Ooh, la, la (DJ, DJ)
[03:13.03] Ooh, la, la
[03:15.40] Ooh, la- la, la
[03:17.40] Ooh- ooh
[03:19.76] Ooh- ooh, la, la, ah, oui, oui
[03:22.96] Ooh- la- la- la- la, la
[03:25.84] La- la- la- la- la- la- la
[03:28.91] Ah, oui- ah, oui- ah
[03:32.57] Ah- ah, oui, oui
[03:34.92]

**Comment by 0x7d4** [comment]
It should be solved now

**Comment by calm3285** [comment]
the fetch issue got solved, but i notice that it only works right if the name artis isnt in lowcase

but the plain lyrics feature is still missing

python __main__.py --allow-plain "Run The Jewels ooh la la" -v
DEBUG:syncedlyrics:Looking for an LRC on Lrclib
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): lrclib.net:443
DEBUG:urllib3.connectionpool:https://lrclib.net:443 "GET /api/search?q=Run+The+Jewels+ooh+la+la HTTP/1.1" 200 64946
DEBUG:urllib3.connectionpool:https://lrclib.net:443 "GET /api/get/2194623 HTTP/1.1" 200 6306
INFO:syncedlyrics:synced-lyrics found for "Run The Jewels ooh la la" on Lrclib
[00:04.91] Uh, hey (oh, shit)
[00:11.33] Ooh, la la, ah, oui oui
[00:13.87] Ooh, la la, ah, oui oui (hey)
[00:16.65] Ooh, la la, ah, oui oui (hey)
[00:19.33] Ooh, la la, ah, oui oui (let's go)
[00:22.22] Ooh, la la, ah, oui oui (go, go, go, go)
[00:25.08] Ooh, la la, ah, oui oui (go, go, go)
[00:27.79] Ooh, la la, ah, oui oui
[00:30.60] Ooh, la la
[00:32.53] Lookin' for M's like I lost a friend
[00:35.06] Jump out of my bed like, "Where that bread"
[00:36.96] You gon' hold a egg, waiter bring the check
[00:38.99] When we talk, we Kalashnikov, keep us in your thoughts
[00:41.82] Fully dressed at the crack of dawn, weapons letting off
[00:44.58] I can hear them from the block, see them creeping through the fog
[00:47.48] Season's greetings, now feeding season can start, oh my god
[00:50.26] Look alive, lookin' like I live life on the crooked line
[00:53.13] Doin' fine, you want maximum stupid, I am the guy
[00:56.03] First of all, fuck the fuckin' law, we is fuckin' raw
[00:58.74] Steak tartare, oysters on the half-shell, sushi bar
[01:01.57] Life a bitch, and the pussy fish, still fucked her raw
[01:04.46] I'm a dog, I'm a dirty dog, ha ha ha ha ha
[01:07.19] Ol' dirty bastard, go in your jaw, shimmy, shimmy, ya
[01:10.08] Got the semi in the hemi, go and gimme, gimme, ya
[01:12.73] Pugilistic, my linguistics are Jeru the Damaja
[01:15.56] And I rap it pornographic, bitch, set up the camera
[01:18.60] Ooh, la la, ah, oui oui (hey)
[01:21.77] Ooh, la la, ah, oui oui (ah, oui oui)
[01:24.38] Ooh, la la, ah, oui oui
[01:27.01] Ooh, la la, ah, oui oui (got some weed, got some weed)
[01:30.37] Ooh, la la, ah, oui oui (got some weed, got some, ayy)
[01:33.30] Ooh, la la, ah, oui oui
[01:35.45] Ooh, la la, ah, oui oui (I need a bottle of Moët, ho, come on)
[01:38.54] Ooh, la la, ah, oui oui (wassup)
[01:41.25] You covet disruption, I got you covered, I'm bustin'
[01:44.27] My brother's a runner, he's crushin', it's no discussion
[01:46.87] I used to be munchkin, I wasn't 'posed to be nothin'
[01:49.84] Y'all fuckers corrupted, or up to somethin disgustin'
[01:52.57] My pockets are plump for the season, I love to cuff 'em
[01:55.37] I'ma afraid of nothin' but nothin', the same as somethin'
[01:58.28] Warmongers are dumpin' a pointed click at your pumpkin (look out)
[02:00.93] You're somethin' scrumptious, so put your kids in the oven
[02:04.03] Fuck a king or queen and all of their loyal subjects
[02:06.78] I'll pull my penis out and I piss on their shoes in public
[02:09.56] People, we the pirates, the pride of this great republic
[02:12.43] No matter what you order, muhfucka, we're what you're stuck wit
[02:15.27] I used to love Bruce, but livin' my vida loca
[02:17.92] Help me understand, I'm probably more of a Joker
[02:20.86] When we usher in chaos, just know that we did it smilin'
[02:23.60] Hannibal's on this island, inmates run the asylum
[02:26.67] Ooh, la la, ah, oui oui (hey)
[02:29.33] Ooh, la la, ah, oui oui (hey)
[02:32.17] Ooh, la la, ah, oui oui (hey)
[02:35.06] Ooh, la la
[02:36.91] DJ, DJ
[02:39.39] Ooh, la la
[02:41.33] Ooh, la, la, la, la
[02:43.72] Ooh, ooh
[02:46.07] Ooh, la la, ah, oui oui
[02:49.02] La, la, la, la, la
[02:51.63] Ah, oui, ah, oui, ah
[02:55.74] Ah, ah, ah, oui, oui
[03:00.03]

**Comment by 0x7d4** [comment]
You are not using the latest version since it should search on Musixmatch now first. You can filter it using `-p lrclib` if you want.
Also since the goal of this lib is finding a LRC format,  allow-plain only returns a plain one (if implemented for the provider) when the synced version was not found. I think plain lyrics is easy to find with genius API or a simple scrap from Azlyrics or similar providers.

I will make commit for lower case different result as well since rapidfuzz v3 removed pre processing. You can try the latest by cloning the repo (uninstall the previous versions before)
